# Exploring the Response Variable and Concluding the Initial Exploration

Import packages

In [1]:
import numpy as np #numerical computation
import pandas as pd #data wrangling
import matplotlib.pyplot as plt #plotting package
#Next line helps with rendering plots
%matplotlib inline
import matplotlib as mpl #add'l plotting functionality
mpl.rcParams['figure.dpi'] = 400 #high res figures

In [2]:
df = pd.read_csv('../../Data/Chapter_1_cleaned_data.csv')

In [3]:
df['default payment next month'].mean()

0.2217971797179718

In [4]:
df.groupby('default payment next month')['ID'].count()

default payment next month
0    20750
1     5914
Name: ID, dtype: int64

# Introduction to Scikit-Learn

In [5]:
#Import the class
from sklearn.linear_model import LogisticRegression

In [6]:
#Create an object
my_lr = LogisticRegression()

In [7]:
#Examine it
my_lr

LogisticRegression()

In [8]:
#Instantiate while specifying keyword arguments
my_new_lr = LogisticRegression(penalty='l2', dual=False,
                               tol=0.0001, C=1.0, fit_intercept=True,
                               intercept_scaling=1, class_weight=None,
                               random_state=None, solver='lbfgs',
                               max_iter=100, multi_class='auto',
                               verbose=0, warm_start=False,
                               n_jobs=None, l1_ratio=None)

In [9]:
my_new_lr

LogisticRegression()

In [10]:
my_new_lr.C = 0.1
my_new_lr.solver = 'liblinear'

In [11]:
my_new_lr

LogisticRegression(C=0.1, solver='liblinear')

In [12]:
X = df['EDUCATION'][0:10].values.reshape(-1,1)
X

array([[2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [3],
       [3]])

In [13]:
y = df['default payment next month'][0:10].values
y

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
my_new_lr.fit(X, y)

LogisticRegression(C=0.1, solver='liblinear')

In [15]:
new_X = df['EDUCATION'][10:20].values.reshape(-1,1)
new_X

array([[3],
       [1],
       [2],
       [2],
       [1],
       [3],
       [1],
       [1],
       [1],
       [3]])

In [16]:
my_new_lr.predict(new_X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
df['default payment next month'][10:20].values

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0])