# Boolean masks

In [1]:
import numpy as np
from numpy.random import default_rng

In [2]:
rg = default_rng(12345)

In [3]:
random_integers = rg.integers(low=1,high=5,size=100)

In [4]:
random_integers[:5]

array([3, 1, 4, 2, 1])

In [5]:
is_equal_to_3 = random_integers == 3

In [6]:
is_equal_to_3[:5]

array([ True, False, False, False, False])

In [7]:
sum(is_equal_to_3)

31

In [8]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3])