In [1]:
import numpy as np #numerical computation
import pandas as pd #data wrangling
import matplotlib.pyplot as plt #plotting package
#Next line helps with rendering plots
%matplotlib inline
import matplotlib as mpl #add'l plotting functionality
import seaborn as sns #a fancy plotting package
mpl.rcParams['figure.dpi'] = 400 #high res figures

Load data

In [2]:
df = pd.read_csv('../../Data/Chapter_1_cleaned_data.csv')

In [3]:
def sigmoid(X):
    Y = 1 / (1 + np.exp(-X))
    return Y

# Activity 3: Fitting a Logistic Regression Model and Directly Using the Coefficients

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    df[['PAY_1', 'LIMIT_BAL']].values,
    df['default payment next month'].values,
    test_size=0.2, random_state=24)

In [6]:
print(X_train.shape)
print(X_test.shape)

(21331, 2)
(5333, 2)


In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
lr_model = LogisticRegression(solver='liblinear')

In [9]:
lr_model

LogisticRegression(solver='liblinear')

In [10]:
lr_model.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [11]:
y_pred = lr_model.predict(X_test)

In [12]:
y_pred_proba = lr_model.predict_proba(X_test)

In [13]:
print(lr_model.coef_, lr_model.intercept_)

[[ 8.27451187e-11 -6.80876727e-06]] [-6.57647457e-11]


In [14]:
np.ones((X_test.shape[0],1)).shape

(5333, 1)

In [15]:
ones_and_features = np.hstack(
    [np.ones((X_test.shape[0],1)), X_test])
ones_and_features

array([[ 1.0e+00,  2.0e+00,  1.6e+05],
       [ 1.0e+00,  1.0e+00,  5.0e+04],
       [ 1.0e+00, -1.0e+00,  2.0e+05],
       ...,
       [ 1.0e+00, -1.0e+00,  5.0e+04],
       [ 1.0e+00,  1.0e+00,  2.3e+05],
       [ 1.0e+00,  2.0e+00,  1.0e+05]])

In [16]:
intercept_and_coefs = np.concatenate(
    [lr_model.intercept_.reshape(1,1), lr_model.coef_], axis=1)
intercept_and_coefs

array([[-6.57647457e-11,  8.27451187e-11, -6.80876727e-06]])

In [17]:
X_lin_comb = np.dot(intercept_and_coefs,
                    np.transpose(ones_and_features))

In [18]:
y_pred_proba_manual = sigmoid(X_lin_comb)

In [19]:
y_pred_manual = y_pred_proba_manual >= 0.5

In [20]:
y_pred.shape

(5333,)

In [21]:
y_pred_manual.shape

(1, 5333)

In [22]:
np.array_equal(y_pred.reshape(1,-1), y_pred_manual)

True

In [23]:
from sklearn.metrics import roc_auc_score

In [24]:
y_test.shape

(5333,)

In [25]:
y_pred_proba_manual.shape

(1, 5333)

In [26]:
roc_auc_score(y_test, y_pred_proba_manual.reshape(y_pred_proba_manual.shape[1],))

0.627207450280691

In [27]:
roc_auc_score(y_test, y_pred_proba[:,1])

0.627207450280691